# Generated by Django 4.1 on 2022-09-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=30)),
                ('tiempoRelacion', models.CharField(max_length=30)),
                ('estadoRelacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
    ]
